apiVersion: v1
kind: Service
metadata:
  name: secured-springboot-rest
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    deploymentConfig: secured-springboot-rest
  type: ClusterIP