---
kind: Service
apiVersion: v1
metadata:
  name: sso
  labels:
    application: sso
    component: server
  annotations:
    description: The web server's http port.
spec:
  ports:
  - name: port-sso
    port: 8080
    targetPort: 8080
  selector:
    deploymentConfig: sso
  type: ClusterIP