---
kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-jboss
    description: Application template for SpringBoot REST + Red Hat SSO demo application.
    tags: javaee,java,jboss,xpaas,sso
    version: 1.3.2
  name: springboot-rest
labels:
  template: springboot-rest
  xpaas: 1.3.2
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  value: springboot-rest
  required: true
- description: Git source URI for application
  name: SOURCE_REPOSITORY_URL
  value: https://github.com/alesj/quick_rest_springboot-tomcat
  required: true
- description: Git branch/tag reference
  name: SOURCE_REPOSITORY_REF
  value: sso
  required: false
- description: GitHub trigger secret
  name: GITHUB_WEBHOOK_SECRET
  from: "[a-zA-Z0-9]{8}"
  generate: expression
  required: true
- description: Generic build trigger secret
  name: GENERIC_WEBHOOK_SECRET
  from: "[a-zA-Z0-9]{8}"
  generate: expression
  required: true
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
  value: ''
  required: false
- description: The URL for the SSO server (e.g. https://secure-sso-myproject.example.com/auth).  This
    is the URL through which the user will be redirected when a login or token is
    required by the application.
  name: SSO_URL
  value: https://secure-sso-springboot-rest.b795.dev-preview-stg.openshiftapps.com
  required: true
