---
kind: Template
apiVersion: v1
metadata:
  annotations:
    iconClass: icon-jboss
    description: Application template for SpringBoot REST + Red Hat SSO demo application.
    tags: javaee,java,jboss,xpaas,sso
    version: 1.3.2
  name: secured-springboot-rest
labels:
  template: secured-springboot-rest
  xpaas: 1.3.2
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  value: secured-springboot-rest
  required: true
- description: 'Custom hostname for http service route.  Leave blank for default hostname,
    e.g.: <application-name>-<project>.<default-domain-suffix>'
  name: HOSTNAME_HTTP
  value: ''
  required: false
- description: The URL for the SSO server (e.g. https://secure-sso-myproject.example.com/auth).  This
    is the URL through which the user will be redirected when a login or token is
    required by the application.
  name: SSO_URL
  value: https://secure-sso-secured-springboot-rest.b795.dev-preview-stg.openshiftapps.com
  required: true
